### ISSUE TITLE
Fails to parse path to PHP if symlink is relative

### ISSUE THREAD

**Issue by Drarok** [Drarok/phpicker#3]

**Comment by olorton** [comment]
$ phpicker
    Traceback (most recent call last):
      File "/Users/oliver/.dotfiles/bin/phpicker", line 105, in <module>
        display_versions(paths)
      File "/Users/oliver/.dotfiles/bin/phpicker", line 82, in display_versions
        current_version = get_current_version()
      File "/Users/oliver/.dotfiles/bin/phpicker", line 78, in get_current_version
        return get_version_from_path(os.path.dirname(real_path))
      File "/Users/oliver/.dotfiles/bin/phpicker", line 45, in get_version_from_path
        raise KeyError('Path %s is not recognised' % path)
    KeyError: u'Path /usr/local/bin/../Cellar/php56/5.6.13_3/bin is not recognised'
    $ ld -ls $(which php)
    ld: library not found for -ls
    $ ls ls $(which php)
    ls: ls: No such file or directory
    21240668 -rwxr-xr-x  1 oliver  admin    11M 28 Sep 15:05 /usr/local/opt/php56/bin/php*
    $ which -a php
    /usr/local/opt/php56/bin/php
    /usr/local/bin/php
    /usr/bin/php
    $ ls -la /usr/local/bin/php
    21240704 lrwxr-xr-x  1 oliver  admin    32B 28 Sep 15:05 /usr/local/bin/php@ -> ../Cellar/php56/5.6.13_3/bin/php
    $ rm /usr/local/bin/php
    $ ln -s /usr/local/Cellar/php56/5.6.13_3/bin/php /usr/local/bin/php
    $ phpicker
    * 5.6.13_3
      5.6.6
      system
    $

**Comment by Drarok** [comment]
This should now be fixed by [v0.3](https://github.com/Drarok/phpicker/releases/tag/v0.3)
